name: Earthquake Toot workflow

on:
  workflow_dispatch:

jobs:
  toot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Request earthquake data and write into Json file
        run: |-
          cd /home/runner/work/vancouver_earthquake/vancouver_earthquake/api 
          python3 earthquake_api.py
          
      - name: Install dependencies 
        run: |-
          cd /home/runner/work/vancouver_earthquake/vancouver_earthquake
          pip3 install Mastodon.py
          python3 -m pip install --upgrade Pillow

      - name: Post earthquake and map into Mastodon
        run: |-
          cd /home/runner/work/vancouver_earthquake/vancouver_earthquake
          python3 toot.py
        env:
          ACCOUNT_EMAIL: ${{ secrets.ACCOUNT_EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          MASTODON_SERVER: ${{ secrets.MASTODON_SERVER }}
